#!/bin/bash

echo

echo "------- uninstalling daf_agent executable ----------"
/opt/daf/daf_agent -service stop delete

echo "------- deleting installed files and databases ----------"
rm -rf /opt/daf



