#!/bin/bash

# -------------------------------------------------------------------------------------------------------------------- # 
#                                                                                                                      #
# install_daf_server                                                                                                   #
#                                                                                                                      #
# This file is part of the daf test automation programme.                                                              #
#                                                                                                                      #
# Purpose:   performs the initial install of the DAF server code                                                       #
#                                                                                                                      #
# -------------------------------------------------------------------------------------------------------------------- #

err_report() {
    echo "Error on line $1"
}

trap 'err_report $LINENO; exit 1' ERR

# --------------------------------------------------------------------------------------------#
# usage()
#
# print usage info
# --------------------------------------------------------------------------------------------#
function usage {
  echo 
  echo "install_daf_server [-d]"
  echo
  echo "   -d           an optional paramater that indicates the default DAF ports are to be"
  echo "                used for the LAMPP Apache and MySQL applications.  These are 8901 and 8902."
  echo "                If -d is not specified, then the script will prompt the user to enter the"
  echo "                desired ports from the keyboard, or simply accept the defaults"
  echo
  echo "Performs an initial install of the DAF server code, including the LAMPP stack and DAF server daemon"
  echo
}

# --------------------------------------------------------------------------------------------#
#
# parse command line options
#
# we only allow as -d as a command line option - this will set the LAMPP Apache and SQL
# ports to the DAF defaults
#
# --------------------------------------------------------------------------------------------#

while getopts "dh" OPT
do
    case $OPT in
    d)
    USE_DEFAULT_PORTS=1
      ;;
    h)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option $OPT - exiting"
      usage
      exit 1
      ;;
    esac
done

ApachePort=8901
MysqlPort=8902
PASSWORD=passw0rd

LOGFILE=/tmp/dafinstall.log
rm -f /tmp/dafinstall.log

XAMPPDIR=/opt/lampp
DAFWEB=/opt/lampp/htdocs/daf
HOSTNAME=`hostname -s`
FULLHOSTNAME=`hostname`

# ----------------------------------------------------------
# we need root to run this script
# ----------------------------------------------------------

if test "`id -u`" -ne 0
then
   echo "You need to be root to install the DAF server" | tee -a $LOGFILE
   exit 1
fi

# ----------------------------------------------------------
# This install only works on Linux
# ----------------------------------------------------------
if [[ `uname` != "Linux" ]]
then
  echo "This installation script must be run on a Linux box - this machine is " `uname` | tee -a $LOGFILE
  exit 1
fi

# ----------------------------------------------------------
# is this a 32 bit or 64 bit server?
# ----------------------------------------------------------

uname -a | grep x86_64 2>/dev/null 1>/dev/null
if [[ $? -eq 0 ]]
then 
   CPUBITS=64
   XAMPINSTALLER=xampp-linux-x64-5.6.19-0-installer.run
else
   CPUBITS=32
   XAMPINSTALLER=xampp-linux-5.6.19-0-installer.run
fi

echo "$FULLHOSTNAME is a " $CPUBITS "bit machine" | tee -a $LOGFILE

# ----------------------------------------------------------
# Try and find out what Linux release this is
# ----------------------------------------------------------

if [[ -f "/etc/redhat-release" ]]
then
   LINUXRELEASE=Redhat 
   echo "This is a $LINUXRELEASE distribution" | tee -a $LOGFILE
   cat /etc/issue 2>/dev/null | tee -a $LOGFILE
elif [[ -f "/etc/fedora_version" ]]
then
   LINUXRELEASE=Fedora  
   echo "This is a $LINUXRELEASE distribution" | tee -a $LOGFILE
   cat /etc/issue 2>/dev/null | tee -a $LOGFILE
elif [[ -f "/etc/SuSE_version" ]]
then
   LINUXRELEASE=SuSE
   echo "This is a $LINUXRELEASE distribution" | tee -a $LOGFILE
   cat /etc/issue 2>/dev/null | tee -a $LOGFILE
else
   if [[ ! -z "$USE_DEFAULT_PORTS" ]]
   then
     echo "Cannot determine what type of Linux distribution is running on this server (Ubuntu will be assumed) - do you want to continue (y/n)?" | tee -a $LOGFILE
     read  answer
     case $answer in
    	yes|Yes|y)
                echo "Assuming Ubuntu..."  | tee -a $LOGFILE
                LINUXRELEASE=Ubuntu
		;;
	    *)
                echo "Not continuing..."  | tee -a $LOGFILE
                exit
		;;
      esac
   else
     echo "Cannot determine what type of Linux distribution is running on this server (Ubuntu will be assumed)"
     LINUXRELEASE=Ubuntu
   fi    
fi


# ----------------------------------------------------------
# is there an existing DAF server installation on this machine
# if so, it must be removed before we install this new one
# ----------------------------------------------------------

if [[ -d $DAFWEB ]] 
then
  echo "There appears to be a DAF installation already present on this test host - cannot proceed!"
  echo "An existing DAF installation can be un-installed using the /opt/uninstall_daf_server script"
  echo "Note: this will delete all existing DAF test results - save a backup of each project if you"
  echo "wish to preserve these results"
  exit 1;
fi

# ----------------------------------------------------------
# Find out which ports we are to use for Apache and MySql
# The defaults are 8901 (Apache) and 8902 (MySql)
# ----------------------------------------------------------

thisdir=`pwd`
mkdir -p /opt/daf

if [[ ! -z "$USE_DEFAULT_PORTS" ]]
then
  echo "The default ports will be used in this install"
else
	echo "Do you wish to use the default port of $MysqlPort for the DAF SQL database (Y/n)?"
	read  answer
	case $answer in
		yes|Yes|y)
	                echo "Using port $MysqlPort for the DAF SQL database"  | tee -a $LOGFILE
			;;
		no|n)
	                echo "Enter the port number to be used for the DAF SQL database:"
	                read  MyslqPort
	                echo "Using port $MysqlPort for the DAF SQL database"  | tee -a $LOGFILE
			;;
		*)
	                echo "Using port $MysqlPort for the DAF SQL database"  | tee -a $LOGFILE
			;;
	esac
	
	echo "Do you wish to use the default port of $ApachePort for the DAF Web Server (Y/n)?"
	read  answer
	case $answer in
		yes|Yes|y)
	                echo "Using port $ApachePort for the DAF Web Server"  | tee -a $LOGFILE
			;;
		no|n)
	                echo "Enter the port number to be used for the DAF Web Server:"
	                read  ApachePort
	                echo "Using port $MysqlPort for the DAF SQL database"  | tee -a $LOGFILE
			;;
			
		*)
	                echo "Using port $ApachePort for the DAF Web Server"  | tee -a $LOGFILE
			;;
	esac
fi

# ----------------------------------------------------------
# Install XAMPP
# ----------------------------------------------------------

today=`date`
echo "Installing DAF on $HOSTNAME on $today" >>$LOGFILE
echo
echo "Installing Xampp" | tee -a $LOGFILE
cd xampp
./$XAMPINSTALLER --mode unattended

echo "Stopping Xampp" | tee -a $LOGFILE
/opt/lampp/lampp stopapache | tee -a $LOGFILE
/opt/lampp/lampp stopmysql | tee -a $LOGFILE

cd $thisdir

# ----------------------------------------------------------
# Install the php scripts part of DAF - these go in /opt/lampp/htdocs/daf
# ----------------------------------------------------------

echo "------- installing DAF php scripts  ----------" | tee -a $LOGFILE
mkdir -p $XAMPPDIR/htdocs/daf 2>&1 | tee -a $LOGFILE
tar -xzf daf_web.tar.gz -C $DAFWEB 2>&1 | tee -a $LOGFILE

# ----------------------------------------------------------
# Set the port values for Apache and MySql in the
# /opt/lampp/etc/my.conf file, /opt/lampp/lampp, /opt/lampp/etc/httpd.conf
# ----------------------------------------------------------

echo "Modify mysql to use port $MysqlPort"  2>&1 | tee -a $LOGFILE
sed "s%3306%$MysqlPort%g" -i $XAMPPDIR/etc/my.cnf  2>&1 | tee -a $LOGFILE
sed "s%if testport 3306%if testport $MysqlPort%" -i $XAMPPDIR/lampp 2>&1 | tee -a $LOGFILE

echo "Modify Apache to use port $ApachePort"  2>&1 | tee -a $LOGFILE
sed "s%Listen 80%Listen $ApachePort%" -i $XAMPPDIR/etc/httpd.conf  2>&1 | tee -a $LOGFILE
sed "s%if testport 80%if testport $ApachePort%" -i $XAMPPDIR/lampp  2>&1 | tee -a $LOGFILE

# ----------------------------------------------------------
# Adjust settings in /opt/lampp/etc/extra/httpd-xampp.conf so that 
# hosts other than the localhost can access phpmyadmin
# ----------------------------------------------------------

sed "s%Require local%Require all granted%" -i $XAMPPDIR/etc/extra/httpd-xampp.conf  2>&1 | tee -a $LOGFILE

# ----------------------------------------------------------
# Check that the XAMPP install is good - run PHP
# ----------------------------------------------------------

if $XAMPPDIR/bin/php -v > /dev/null 2>&1
then
  :
else
  echo "$XAMPPDIR/lampp/bin/php -v not running without error - cannot proceed - please check installation pre-requisites"  2>&1 | tee -a $LOGFILE
  exit 1 
fi

# ----------------------------------------------------------
# Start up lampp
#-----------------------------------------------------------

echo "Starting Xampp"  2>&1 | tee -a $LOGFILE
$XAMPPDIR/lampp startapache 2>&1 | tee -a $LOGFILE
$XAMPPDIR/lampp startmysql  2>&1 | tee -a $LOGFILE

# ----------------------------------------------------------
# Unpack the C source code and SQL initialisation scripts  
# ----------------------------------------------------------

echo "------- Unpack C source code and SQL initilisation scripts ---" | tee -a $LOGFILE
mkdir -p $thisdir/server
tar -xzf daf_server.tar.gz -C $thisdir/server

# ----------------------------------------------------------
# Create users and DAF tables the MySql database
#-----------------------------------------------------------

echo "------- creating DAF_admin user ----------"  2>&1 | tee -a $LOGFILE
$XAMPPDIR/bin/mysql <$thisdir/server/create_daf_admin  2>&1 | tee -a $LOGFILE
if [[ $? -ne 0 ]]
then
  exit 1
fi

echo "------- creating DAF database user ----------"
$XAMPPDIR/bin/mysql <$thisdir/server/create_daf_database 2>&1 | tee -a $LOGFILE
if [[ $? -ne 0 ]]
then
  exit 1
fi

echo "------- creating DAF tables  ----------"
$XAMPPDIR/bin/mysql <$thisdir/server/create_daf_tables 2>&1 | tee -a $LOGFILE
if [[ $? -ne 0 ]]
then
  exit 1
fi

echo "------- creating DAF table predefined contents  ----------"
$XAMPPDIR/bin/mysql <$thisdir/server/create_daf_table_contents 2>&1 | tee -a $LOGFILE
if [[ $? -ne 0 ]]
then
  exit 1
fi


echo "------- creating DAF master test user  ----------"
$XAMPPDIR/bin/mysql <$thisdir/server/create_master_test_user 2>&1 | tee -a $LOGFILE
if [[ $? -ne 0 ]]
then
  exit 1
fi

mkdir $XAMPPDIR/htdocs/daf/backup 2>&1 | tee -a $LOGFILE
chown nobody $XAMPPDIR/htdocs/daf/ 2>&1 | tee -a $LOGFILE

# ----------------------------------------------------------
# Compile and install the C code for the daf_server daemon
# ----------------------------------------------------------

echo "------- compiling and installing DAF server daemon  ----------" | tee -a $LOGFILE
cd server

# Modify afconstants.h so that it contains the correct host name and password
cat afconstants.h | grep -v SQLSERVERNAME | grep -v DEFAULT_SQLPASSWORD >afconstants.h.temp
#echo "#define DEFAULT_SQLSERVERNAME \"$HOSTNAME\"" >afconstants.h
echo "#define DEFAULT_SQLSERVERNAME \"localhost\"" >afconstants.h
echo "#define DEFAULT_SQLPASSWORD \"passw0rd\"" >>afconstants.h
cat afconstants.h.temp >>afconstants.h
rm afconstants.h.temp

# since daf uses the SQL libraries and we want to use the particular libraries in the LAMPP distribution
# we need to update the library path
if test -z $LD_LIBRARY_PATH
then
        export LD_LIBRARY_PATH=$XAMPPDIR/lib
else
        export LD_LIBRARY_PATH=$XAMPPDIR/lib:$LD_LIBRARY_PATH
fi
echo "LD_LIBRARY_PATH was set to $LD_LIBRARY_PATH" | tee -a $LOGFILE

make -f Makefile clean all
if [[ $? -ne 0 ]]
then
  exit 1
fi
cd $thisdir

echo "------- installing DAF executable ----------" | tee -a $LOGFILE

cd $thisdir/server
./daf -service delete stop install start 2>&1 | tee -a $LOGFILE
if [[ $? -ne 0 ]]
then
  echo "Problem starting the DAF service - cannot proceed - refer to $LOGFILE for failure details" 2>&1 | tee -a $LOGFILE
  exit 1;
fi

# ----------------------------------------------------------
# Copy the daf_licence utility to /opt/daf
# ----------------------------------------------------------

cp ./daf_licence /opt/daf 2>&1 | tee -a $LOGFILE
# make the licence file writeable
chmod 777 /opt/daf 2>&1 | tee -a $LOGFILE         

# ----------------------------------------------------------
# Copy the uninstall script to /opt
# ----------------------------------------------------------

echo "------- copying uninstall script to /opt ---" | tee -a $LOGFILE
cp -f $thisdir/server/uninstall_daf_server /opt 2>&1 | tee -a $LOGFILE
cd $thisdir

# TEMP TEMP allow all hosts with user root to access mysql
echo "INSERT INTO user (Host, User, Password, Select_priv, Insert_priv, Update_priv, Delete_priv, Create_priv, Drop_priv, Reload_priv, Shutdown_priv, \
                          Process_priv, File_priv, Grant_priv, References_priv, Index_priv, Alter_priv, Show_db_priv, Super_priv, Create_tmp_table_priv, \
                          Lock_tables_priv, Execute_priv, Repl_slave_priv, Repl_client_priv, Create_view_priv, Show_view_priv, Create_routine_priv, \
                          Alter_routine_priv, Create_user_priv, Event_priv, Trigger_priv, Create_tablespace_priv, ssl_type, max_questions, max_updates, \
                          max_connections, max_user_connections, plugin, authentication_string, password_expired, is_role, default_role, max_statement_time) \
                          VALUES ('%', 'root', '*74B1C21ACE0C2D6B0678A5E503D2A60E8F9651A3', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', \
                          'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', '', 0, 0, 0, 0, '', '', 'Y', 'Y', '', '0.000000');" | /opt/lampp/bin/mysql -uroot mysql 2>&1 | tee -a $LOGFILE
if [[ $? -ne 0 ]]
then
  exit 1
fi

# ----------------------------------------------------------
# Fix up the MySql root password
# ----------------------------------------------------------

echo "------- setting up MySQL - setting root password to $PASSWORD ---" | tee -a $LOGFILE
echo "Setting new MySQL root password to $PASSWORD" 2>&1 | tee -a $LOGFILE
echo "update user set Password=password('$PASSWORD') where User = 'root';" | $XAMPPDIR/bin/mysql -uroot mysql  2>&1 | tee -a $LOGFILE
$XAMPPDIR/bin/mysqladmin reload  2>&1 | tee -a $LOGFILE
if [[ $? -ne 0 ]]
then
  exit 1
fi

# ----------------------------------------------------------
# Fix up the phpmadmin passwords
# ----------------------------------------------------------
sed "s%\$cfg\['Servers'\]\[\$i\]\['password'\] = '';%\$cfg\['Servers'\]\[\$i\]\['password'\] = '$PASSWORD';%" \
    -i $XAMPPDIR/phpmyadmin/config.inc.php 2>&1 | tee -a $LOGFILE

# ----------------------------------------------------------
# Ensure the DAF server starts up when the server is booted
# ----------------------------------------------------------

echo "------- Ensure the DAF server starts up when the server is booted ---" | tee -a $LOGFILE
ln -sf /opt/lampp/lampp /etc/init.d/lampp
if [[ $LINUXRELEASE == "Redhat" ]] 
then
   chkconfig --add lampp
elif [[ $LINUXRELEASE == "Suse" ]]
then
   chkconfig lampp 2345
elif [[ $LINUXRELEASE == "Ubuntu" ]]
then
   update-rc.d lampp start 80 2 3 4 5 . stop 30 0 1 6 .
else
   chkconfig lampp on
fi

# ----------------------------------------------------------
# Summarise the various URLs etc for the user
# ----------------------------------------------------------

echo 
echo
echo "The DAF server has now been successfully installed" | tee -a $LOGFILE
echo 
echo "Now connect a web browser to    http://${FULLHOSTNAME}:${ApachePort}/daf    to complete the installation"  2>&1 | tee -a $LOGFILE
echo "Login with the 'daf administrator' userid, password '$PASSWORD'" | tee -a $LOGFILE
#echo "Use the following licence:" | tee -a $LOGFILE
$thisdir/server/daf_generate_licence >> $LOGFILE
# install the licence so that the user does not have to remember to do so manually
/opt/daf/daf_licence -write_licence /opt/daf/daf_licence_file -licence "`cat /tmp/dafinstall.log | grep "Licence is" | cut -f3-12 -d' '`"
echo | tee -a $LOGFILE
echo "Note: phpmyadmin is available at:   http://${FULLHOSTNAME}:${ApachePort}/phpmyadmin/" | tee -a $LOGFILE
echo "Note: mysql is available at port ${MysqlPort}, root user, password $PASSWORD" | tee -a $LOGFILE
echo "Note: the xampp dashboard is available at: http://${FULLHOSTNAME}:${ApachePort}/dashboard/" | tee -a $LOGFILE
echo "Note: the Apache log is at: /opt/lampp/logs/error_log" | tee -a $LOGFILE
echo
echo "Note: run     /opt/lampp/lampp stopapache stopmysql      to stop Apache and MySql" | tee -a $LOGFILE
echo "Note: run     /opt/lampp/lampp startapache startmysql    to start Apache and MySql" | tee -a $LOGFILE
echo "Note: run     /opt/lampp/lampp reloadapache reloadmysql  to restart Apache and MySql" | tee -a $LOGFILE
echo
echo "Note: to deinstall the DAF server, run     /opt/uninstall_daf_server" | tee -a $LOGFILE
echo 
echo
echo "REMINDER: you will have to patch in the threaded MYSQL library into LAMPP by hand"
echo "  cp /usr/lib64/mysql/libmysqlclient_r.so.16 /opt/lampp/lib"
echo "  cd /opt/lampp/lib"
echo "  ln -sf libmysqlclient_r.so.16.0.0 libmysqlclient_r.so"

echo

