/* ------------------------------------------------------------------------------------------------- */
/*  af_mysql.c                                                                                       */
/*                                                                                                   */
/*  Automation Framework MYSQL client interface                                                      */
/*                                                                                                   */
/* ------------------------------------------------------------------------------------------------- */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <mysql.h>
#include "af_mysql.h"
#include "daf_util.h"

#if !defined(MYSQL_VERSION_ID) || MYSQL_VERSION_ID<32224
#define mysql_field_count mysql_num_fields
#endif

int mysqldebug = 0;

void print_result_set(MYSQL_RES *res_set);

void set_sql_debug_flag(bool_t sql_debug_flag)
{

    mysqldebug = sql_debug_flag;

}


/* ------------------------------------------------------------------------------------------------- */
/*                                                                                                   */
/* Function:   perform_query                                                                         */
/*                                                                                                   */
/* Inputs:     sql_connection                                                                        */
/*                                                                                                   */
/*             query        The query that is to be performed                                        */
/*                                                                                                   */
/* Outputs:    none                                                                                  */
/*                                                                                                   */
/* Returns:    void                                                                                  */
/*                                                                                                   */
/* Function:                                                                                         */
/*                                                                                                   */
/* ------------------------------------------------------------------------------------------------- */

int perform_query(char *caller, MYSQL *sql_connection, char *query)
{

#undef  SUBNAME
#define SUBNAME "perform_query"

    int  rc;
    char msg[1024];

    rc = mysql_query(sql_connection, query);

    if (mysqldebug)
    {
        snprintf(msg, sizeof(msg), "%s: %s\n", SUBNAME, query);
        print_msg_to_console(msg);
    }

    if (rc != 0)
    {
        snprintf(msg, sizeof(msg), "%s: MYSQL error %d (%s) reported for query: %s\n",
                 caller, mysql_errno(sql_connection), mysql_error(sql_connection), query);
        print_msg_to_console(msg);
    }

    return rc;

}

/* ------------------------------------------------------------------------------------------------- */
/*                                                                                                   */
/* Function:   print_query                                                                           */
/*                                                                                                   */
/* Inputs:     conn         An existing connection to the MYSQL database, usually set up by          */
/*                          do_connect()                                                             */
/*                                                                                                   */
/*             query        The query that is to be performed                                        */
/*                                                                                                   */
/* Outputs:    none                                                                                  */
/*                                                                                                   */
/* Returns:    void                                                                                  */
/*                                                                                                   */
/* Function:   A template function that will perform an query (SELECT, INSERT etc) and then print    */
/*             the results returned by that query.                                                   */
/*             The routine uses the mysql_store_result() call so that means that the entire contents */
/*             of all the result rows generated by the query will be immediately returned from the   */
/*             server to the client when the query is performed.  This frees up the server, but      */
/*             means you need enough space in the client memory to hold the complete result at once  */
/*             If an error occurs an error message is printed to STDERR                              */
/* ------------------------------------------------------------------------------------------------- */

void print_query (MYSQL *conn,
                  char *query)
{

#undef  SUBNAME
#define SUBNAME "print_query"

    MYSQL_RES    *res_set;
    char         msg[MAX_MSG_LEN];

    if (perform_query(SUBNAME, conn, query) != 0)   /* the query failed */
    {
        return;
    }

    /* the query succeeded; determine whether or not it returns data */

    res_set = mysql_store_result (conn);

    if (res_set == NULL)    /* no result set was returned */
    {
        /* does the lack of a result set mean that an error  occurred or that no result set was returned? */
        if (mysql_field_count(conn) > 0)
        {
            /* a result set was expected, but mysql_store_result() did not return one; this means an error occurred */
            snprintf(msg, sizeof(msg), "%s: result set is unexpectedly empty for query: %s, errno=%d (%s)\n",
                     SUBNAME, query, mysql_errno(conn), mysql_error(conn));
            print_msg_to_console(msg);
        }
        else
        {
            /* no result set was returned; query returned no data (it was not a SELECT, SHOW, DESCRIBE, or EXPLAIN), */
            /* so just report number of rows affected by query */
            snprintf(msg, sizeof(msg), "%s: query: %s: %lu rows affected\n", SUBNAME, query, (unsigned long) mysql_affected_rows (conn));
            print_msg_to_console(msg);
        }
    }
    else      /* a result set was returned */
    {
        /* process rows, then free the result set */
        print_result_set(res_set);
        mysql_free_result(res_set);
    }
}

/* ------------------------------------------------------------------------------------------------- */
/*                                                                                                   */
/* Function:   print_dashes                                                                          */
/*                                                                                                   */
/* Inputs:     res_set        the result set returned by a query, eg as provided by                  */
/*                            mysql_store_result()                                                   */
/*                                                                                                   */
/* Outputs:    none                                                                                  */
/*                                                                                                   */
/* Returns:    void                                                                                  */
/*                                                                                                   */
/* Function:                                                                                         */
/*                                                                                                   */
/* Prints the dashes needed by print_result_set() as used by the standard box output format          */
/* ------------------------------------------------------------------------------------------------- */

void print_dashes (MYSQL_RES *res_set)
{

    MYSQL_FIELD   *field;
    unsigned int  i, j;

    mysql_field_seek (res_set, 0);
    fputc ('+', stdout);

    for (i = 0; i < mysql_num_fields (res_set); i++)
    {
        field = mysql_fetch_field (res_set);

        for (j = 0; j < field->max_length + 2; j++)
        {
            fputc ('-', stdout);
        }

        fputc ('+', stdout);
    }

    fputc ('\n', stdout);
}

/* ------------------------------------------------------------------------------------------------- */
/*                                                                                                   */
/* Function:   print_result_set                                                                      */
/*                                                                                                   */
/*                                                                                                   */
/* Inputs:     res_set      the result set returned by a query, eg as provided by                    */
/*                          mysql_store_result()                                                     */
/*                                                                                                   */
/* Outputs:    none                                                                                  */
/*                                                                                                   */
/* Returns:    void                                                                                  */
/*                                                                                                   */
/* Function:                                                                                         */
/*                                                                                                   */
/* Prints the contents of a result_set in the standard box format used by MYSQL, eg                  */
/*     +------------+---------------+-------------+                                                  */
/*     | last_name  |  first_name   |    town     |                                                  */
/*     +------------+---------------+-------------+                                                  */
/*     | Smith      | John          | London      |                                                  */
/*     | Brown      | William       | Bristol     |                                                  */
/*     +------------+---------------+-------------+                                                  */
/* ------------------------------------------------------------------------------------------------- */

void print_result_set (MYSQL_RES *res_set)
{

    MYSQL_FIELD   *field;
    MYSQL_ROW     row;
    unsigned int  i, col_len;

    /* determine column display widths */
    mysql_field_seek (res_set, 0);

    for (i = 0; i < mysql_num_fields (res_set); i++)
    {
        field = mysql_fetch_field (res_set);
        col_len = strlen (field->name);

        if (col_len < field->max_length)
        {
            col_len = field->max_length;
        }

        if (col_len < 4 && !IS_NOT_NULL (field->flags))
        {
            col_len = 4;  /* 4 = length of the word "NULL" */
        }

        field->max_length = col_len;  /* reset column info */
    }

    print_dashes (res_set);
    fputc ('|', stdout);
    mysql_field_seek (res_set, 0);

    for (i = 0; i < mysql_num_fields (res_set); i++)
    {
        field = mysql_fetch_field (res_set);
        printf (" %-*s |", (int) field->max_length, field->name);
    }

    fputc ('\n', stdout);
    print_dashes (res_set);

    while ((row = mysql_fetch_row (res_set)) != NULL)
    {
        mysql_field_seek (res_set, 0);
        fputc ('|', stdout);

        for (i = 0; i < mysql_num_fields (res_set); i++)
        {
            field = mysql_fetch_field (res_set);

            if (row[i] == NULL)
            {
                printf (" %-*s |", (int) field->max_length, "NULL");
            }
            else if (IS_NUM (field->type))
            {
                printf (" %*s |", (int) field->max_length, row[i]);
            }
            else
            {
                printf (" %-*s |", (int) field->max_length, row[i]);
            }
        }

        fputc ('\n', stdout);
    }

    print_dashes (res_set);
    printf ("%lu rows returned\n", (unsigned long) mysql_num_rows (res_set));
}

/* ------------------------------------------------------------------------------------------------- */
/*                                                                                                   */
/* Function:   do_connect                                                                            */
/*                                                                                                   */
/* Inputs:     caller                                                                                */
/*                                                                                                   */
/*             host_name                                                                             */
/*                                                                                                   */
/*             user_name                                                                             */
/*                                                                                                   */
/*             password                                                                              */
/*                                                                                                   */
/*             db_name                                                                               */
/*                                                                                                   */
/*             port_num                                                                              */
/*                                                                                                   */
/*             socket_name                                                                           */
/*                                                                                                   */
/*             flags e                                                                               */
/*                                                                                                   */
/*             errmsg                                                                                */
/*                                                                                                   */
/*             max_errmsg_len                                                                           */
/*                                                                                                   */
/* Outputs:    none                                                                                  */
/*                                                                                                   */
/* Returns:    conn                                                                                  */
/*                                                                                                   */
/* Function:                                                                                         */
/*                                                                                                   */
/* Closes a database connection                                                                      */
/* ------------------------------------------------------------------------------------------------- */

MYSQL *do_connect (char *caller,
                   char *host_name,
                   char *user_name,
                   char *password,
                   char *db_name,
                   unsigned int port_num,
                   char *socket_name,
                   unsigned int flags,
                   char *errmsg,
                   int max_errmsg_len)
{

#undef  SUBNAME
#define SUBNAME "do_connect"

    MYSQL  *conn; /* pointer to connection handler */


    if ((conn = mysql_init(NULL)) == NULL)
    {
        snprintf(errmsg, max_errmsg_len, "%s: mysql_init() failed (probably out of memory)\n", caller);
        return (NULL);
    }

    if (!mysql_real_connect(conn, host_name, user_name, password,
                            db_name, port_num, socket_name, flags))
    {
        snprintf(errmsg, max_errmsg_len, "%s: mysql_real_connect() failed: %s", caller, mysql_error(conn));
        return (NULL);
    }

    return (conn);     /* connection is established */
}

/* ------------------------------------------------------------------------------------------------- */
/*                                                                                                   */
/* Function:   do_disconnect                                                                         */
/*                                                                                                   */
/* Inputs:     caller                                                                                */
/*                                                                                                   */
/*                          An existing connection to the MYSQL database, usually set up by          */
/*                          do_connect()                                                             */
/*                                                                                                   */
/* Outputs:    none                                                                                  */
/*                                                                                                   */
/* Returns:    void                                                                                  */
/*                                                                                                   */
/* Function:                                                                                         */
/*                                                                                                   */
/* Closes a database connection                                                                      */
/*                                                                                                   */
/* ------------------------------------------------------------------------------------------------- */

void do_disconnect (char *caller,
                    MYSQL *conn)
{

    if (conn != NULL)
    {
        mysql_close(conn);
    }

}

/* ------------------------------------------------------------------------------------------------- */
/*                                                                                                   */
/* Function:   safecat1                                                                              */
/*                                                                                                   */
//* Inputs:    dest      the destination string                                                      */
/*                                                                                                   */
/*             n         the size of the destination string                                          */
/*                                                                                                   */
/*             src       the source string                                                           */
/*                                                                                                   */
/* Outputs:    none                                                                                  */
/*                                                                                                   */
/* Returns:    void                                                                                  */
/*                                                                                                   */
/* Function:                                                                                         */
/*                                                                                                   */
/* Appends the string pointed to by src (including the terminating '\0' character) to the array      */
/* pointed to by dest. The strings may not overlap.  If the appended string contains more than n-1   */
/* bytes including the terminating \0, then only enough bytes are copied from src to fill the n-1    */
/* bytes in dest  and a terminating \0 is placed in the last byte of dest.   This ensures that dest  */
/* is always returned as a terminated string.                                                        */
/* The routine returns the length that the dest string would need to be (excluding the terminating   */
/* \0) to hold the full result of appending src to dest - so if the returned value is greater or     */
/* equal to n then the dest string has been truncated.                                               */
/* ------------------------------------------------------------------------------------------------- */

int safecat1(char *dest, int n, char *src)
{

    char *p, *q;
    int i = strlen(dest);
    int j = strlen(src);
    int l;

    p = dest + i;
    q = src;
    l = i + j;

    while ((i < n-1) && (j > 0))
    {

        *p = *q;
        p++;
        q++;
        i++;
        j--;

    }

    *p = 0;

    return l;

}

/* ------------------------------------------------------------------------------------------------- */
/*                                                                                                   */
/* Function:   perform_update                                                                        */
/*                                                                                                   */
/* Inputs:     caller                                                                                */
/*                                                                                                   */
/*             conn        An existing connection to the MYSQL database, usually set up by           */
/*                         do_connect()                                                              */
/*                                                                                                   */
/*             table       the name of the table that is to be updated                               */
/*                                                                                                   */
/*             fields      array of string names of the fields in the table that are are to be       */
/*                         updated. The array is terminated by a NULL element.                       */
/*                                                                                                   */
/*             value       array of string values for the fields in the table that are are to be     */
/*                         updated.  The array is terminated by a NULL element.                      */
/*                         If a value is set to the magic string XXXX_CURRENT_TIME_XXXX then the     */
/*                         value of that field will be set to NOW() - ie the current datetime value  */
/*                                                                                                   */
/*             where       specifies the contents oontents of the WHERE cause useed in the UPDATE    */
/*                         - a NULL pointer value indicates that no WHERE clause is to be used       */
/*                                                                                                   */
/*             max_msg_len the max length (including the terminating 0) allowed in the errmsg        */
/*                                                                                                   */
/* Outputs:    errmsg      an error message indicating what went wrong if rc=1                       */
/*                                                                                                   */
/* Returns:    rc          0 if the UPDATE was successful, 1 if not (when the errmsg string will     */
/*                         contain a descriptive message indicating what went wrong)                 */
/*                                                                                                   */
/* Function:                                                                                         */
/*                                                                                                   */
/* Updates fields in a given table.  Only the rows selected by the where clause will be updated      */
/*                                                                                                   */
/* number and message.                                                                               */
/*                                                                                                   */
/*    rc = perform_update("sub1", conn,                                                              */
/*                        "AddressBook",                                                             */
/*                        {"FirstName", "Address", NULL},                                            */
/*                        {"Jim",       "12 Acacia Avenune, Wimbledon", NULL},                       */
/*                        "Lastname = 'Smith'",                                                      */
/*                        errmsg,                                                                    */
/*                        sizeof(errmsg));                                                           */
/*                                                                                                   */
/* would update the rows in the AddressBook table that have a value of Smith in the Lastname field,  */
/* and this update would set the FirstName field to Jim and the Address field to 12 Acacia Avenue,   */
/* Wimbledon.  The query generated would be:                                                         */
/*                                                                                                   */
/* UPDATE AddressBook SET FirstName='Jim', Address='12 Acacia Avenue, Wimbledon' WHERE Lastname=     */
/* 'Smith'                                                                                           */
/*                                                                                                   */
/* ------------------------------------------------------------------------------------------------- */

int perform_update(char  *caller,
                   MYSQL *conn,
                   char  *table,
                   char  *fields[],
                   char  *values[],
                   char  *where,
                   char  *errmsg,
                   int   max_msg_len )
{

#undef  SUBNAME
#define SUBNAME "perform_update"

    MYSQL_RES    *res_set;
    int i = 0, rc = 0;
    char  query[1024];
    int   mq = sizeof(query);
    int  toolong = 0;
    errmsg[0] = 0;

    snprintf(query, sizeof(query), "UPDATE %s SET ", table);

    while ((fields[i] != NULL && values[i] != NULL) && (!toolong))
    {

        if (i != 0)
        {
            safecat1(query, sizeof(query), ",");
        }

        if (safecat1(query, sizeof(query), fields[i]) < mq)
        {
            if (strcmp(values[i], "XXXX_CURRENT_TIME_XXXX") == 0)
            {
                if (safecat1(query, sizeof(query), "=NOW()") < mq)
                {
                }
                else
                {
                    toolong = 1;
                }
            }
            else
            {
                if (safecat1(query, sizeof(query), "='") < mq)
                {
                    if (safecat1(query, sizeof(query), values[i]) < mq)
                    {
                        if (safecat1(query, sizeof(query), "'") < mq)
                        {
                        }
                        else
                        {
                            toolong = 1;
                        }
                    }
                    else
                    {
                        toolong = 1;
                    }
                }
                else
                {
                    toolong = 1;
                }
            }
        }
        else
        {
            toolong = 1;
        }

        i++;
    }

    if (safecat1(query, sizeof(query), " WHERE ") < mq)
    {
        if (safecat1(query, sizeof(query), where) < mq)
        {
        }
        else
        {
            toolong = 1;
        }
    }
    else
    {
        toolong = 1;
    }

    if (toolong)
    {
        snprintf(errmsg, max_msg_len, "%s: query string length exceeded maximm allowed length (%d) for query: >>%s<<\n",
                 caller, (int) sizeof(query), query);
        return 1;
    }


    if (perform_query(caller, conn, query) != 0)
    {
        return 1;
    }

    res_set = mysql_store_result(conn);

    if (res_set == NULL)    /* no result set was returned */
    {
        /* does the lack of a result set mean that an error  occurred or that no result set was returned? */
        if (mysql_field_count(conn) > 0)
        {
            /* a result set was expected, but mysql_store_result() did not return one; this means an error occurred */
            snprintf(errmsg, max_msg_len, "%s: no result set returned for query: %s\n", caller, query);
            return 1;
        }
        else
        {
            /* no result set was returned; query returned no data (it was not an UPDATE so this was expected, no action needed) */
        }
    }
    else      /* a result set was returned */
    {
        /* free the result set */
        mysql_free_result(res_set);
    }

    return rc;

}

/* ------------------------------------------------------------------------------------------------- */
/*                                                                                                   */
/* Function:   perform_insert_from_query_string                                                      */
/*                                                                                                   */
/* Inputs:     caller                                                                                */
/*                                                                                                   */
/*             conn        An existing connection to the MYSQL database, usually set up by           */
/*                         do_connect()                                                              */
/*                                                                                                   */
/*             query       the MYSQL query that will do the insert                                   */
/*                                                                                                   */
/*             max_msg_len the max length (including the terminating 0) allowed in the errmsg        */
/*                                                                                                   */
/* Outputs:    errmsg      an error message indicating what went wrong if rc=1                       */
/*                                                                                                   */
/* Returns:    row_id      non 0 if the INSERT was successful, 0 if not (when the errmsg string will */
/*                         contain adescriptive message indicating what went wrong)                  */
/*                                                                                                   */
//*                                                                                                  */
/* Function:                                                                                         */
/*                                                                                                   */
/* Inserts a new row in a given table, according to the query string supplied                        */
/*                                                                                                   */
/*  row_id = perform_insert(conn,                                                                    */
/*                        "AddressBook",                                                             */
/*                        "INSERT AddressBook (FirstName, LastName, Address) VALUES('Jim', 'Smith'," */
/*                        "'12 Acacia Avenue, Wimbledon');"                                          */
/*                        errmsg,                                                                    */
/*                        sizeof(errmsg));                                                           */
/*                                                                                                   */
/* would insert a new row in the AddressBook table and the FirstName, LastName and Address fields    */
/* would have values of Jim, Smith and 12 Acacia Avenune, Wimbledon respectively.      The id of the */
/* row is returned in row_id.   All DAF tables are guaranteed to autoincrement their IDs from 1      */
/* so a zero value indicates an error                                                                */
/* ------------------------------------------------------------------------------------------------- */

int perform_insert_from_query_string(char *caller, MYSQL *conn, char *query, char *errmsg, int max_msg_len)
{

    MYSQL_RES *res_set;

    if (perform_query(caller, conn, query) != 0)
    {
        snprintf(errmsg, max_msg_len, "%s: query (%s) failed, mysql_errno = %d (%s)\n",
                 caller, query, mysql_errno(conn), mysql_error(conn));
        return 0;
    }

    /* the query succeeded; determine whether or not it returns data */

    res_set = mysql_store_result(conn);

    if (res_set == NULL)    /* no result set was returned */
    {
        /* does the lack of a result set mean that an error  occurred or that no result set was returned? */
        if (mysql_field_count(conn) > 0)
        {
            /* a result set was expected, but mysql_store_result() did not return one; this means an error occurred */
            snprintf(errmsg, max_msg_len, "%s: no result set returned for query: %s\n", caller, query);
            return 0;
        }
        else
        {
            /* no result set was returned; query returned no data (it was an INSERT so this was expected - no action needed) */
        }
    }
    else      /* a result set was returned */
    {
        /* free the result set */
        mysql_free_result(res_set);
    }

    return mysql_insert_id(conn);

}

/* ------------------------------------------------------------------------------------------------- */
/*                                                                                                   */
/* Function:   perform_insert                                                                        */
/*                                                                                                   */
/* Inputs:     caller                                                                                */
/*                                                                                                   */
/*                         An existing connection to the MYSQL database, usually set up by           */
/*                         do_connect()                                                              */
/*                                                                                                   */
/*             table       the name of the table that in which the row is to be inserted             */
/*                                                                                                   */
/*             fields      array of string names of the fields in the row that will be inserted      */
/*                         The array is terminated by a NULL element.                                */
/*                                                                                                   */
/*             value       array of string values for the fields in the row that is to be inserted   */
/*                         updated.   The array is terminated by a NULL element.                     */
/*                         If a value is set to the magic string XXXX_CURRENT_TIME_XXXX then the     */
/*                         value of that field will be set to NOW() - ie the current datetime value  */
/*                                                                                                   */
/*             max_msg_len the max length (including the terminating 0) allowed in the errmsg        */
/*                                                                                                   */
/* Outputs:    errmsg      an error message indicating what went wrong if rc=1                       */
/*                                                                                                   */
/* Returns:    rc          0 if the INSERT was successful, 1 if not (when the errmsg string will     */
/*                         contain a descriptive message indicating what went wrong)                 */
/*                                                                                                   */
/* Function:                                                                                         */
/*                                                                                                   */
/* Inserts a new row in a given table.  If not all the field/values are specified then the default   */
/* values for these fields will be used.                                                             */
/*                                                                                                   */
/*    rc = perform_insert(conn,                                                                      */
/*                        "AddressBook",                                                             */
/*                        {"FirstName", "LastName", "Address", NULL},                                */
/*                        {"Jim",       "Smith",    "12 Acacia Avenune, Wimbledon", NULL},           */
/*                        errmsg,                                                                    */
/*                        sizeof(errmsg));                                                           */
/*                                                                                                   */
/* would insert a new row in the AddressBook table and the FirstName, LastName and Address fields    */
/* would have values of Jim, Smith and 12 Acacia Avenune, Wimbledon respectively. The query          */
/* generated would be:                                                                               */
/*                                                                                                   */
/* INSERT AddressBook (FirstName, LastName, Address) VALUES('Jim', 'Smith',                          */
/* '12 Acacia Avenue, Wimbledon')                                                                    */
/*                                                                                                   */
/* ------------------------------------------------------------------------------------------------- */

int perform_insert(char  *caller,
                   MYSQL *conn,
                   char  *table,
                   char  *fields[],
                   char  *values[],
                   char  *errmsg,
                   int   max_msg_len )
{

#undef  SUBNAME
#define SUBNAME "perform_insert"

    int i = 0, ll, rc = 0;

    char  query[1024];
    int   mq = sizeof(query);

    safecpy(errmsg, "", max_msg_len);

    snprintf(query, sizeof(query), "INSERT %s (", table);

    while (fields[i] != NULL)
    {
        if (i != 0)
        {
            safecat1(query, sizeof(query), ",");
        }

        if ((ll = safecat1(query, sizeof(query), fields[i])) < mq)
        {
        }
        else
        {
            snprintf(errmsg, max_msg_len, "%s: query string length (%d) exceeded maximm allowed length (%d) for query: %s\n",
                     caller, ll, (int) sizeof(query), query);
            return 1;
        }

        i++;
    }

    if ((ll = safecat1(query, sizeof(query), ") VALUES('")) < mq)
    {
    }
    else
    {
        snprintf(errmsg, max_msg_len, "%s: query string length (%d) exceeded maximm allowed length (%d) for query: %s\n",
                 caller, ll, (int) sizeof(query), query);
        return 1;
    }

    i = 0;

    while (values[i] != NULL)
    {

        if (i != 0)
        {
            if (strcmp(values[i], "XXXX_CURRENT_TIME_XXXX") == 0)
            {
                safecat1(query, sizeof(query), ",");
            }
            else
            {
                safecat1(query, sizeof(query), ",'");
            }
        }

        if (strcmp(values[i], "XXXX_CURRENT_TIME_XXXX") == 0)
        {
            if ((ll = safecat1(query, sizeof(query), "NOW()")) < mq)
            {
            }
            else
            {
                snprintf(errmsg, max_msg_len, "%s: query string length (%d) exceeded maximm allowed length (%d) for query: %s\n",
                         caller, ll, (int) sizeof(query), query);
                return 1;
            }
        }
        else
        {
            if ((ll = safecat1(query, sizeof(query), values[i])) < mq)
            {
            }
            else
            {
                snprintf(errmsg, max_msg_len, "%s: query string length (%d) exceeded maximm allowed length (%d) for query: %s\n",
                         caller, ll, (int) sizeof(query), query);
                return 1;
            }
        }

        if (strcmp(values[i], "XXXX_CURRENT_TIME_XXXX") != 0)
        {
            if ((ll = safecat1(query, sizeof(query), "'")) < mq)
            {
            }
            else
            {
                snprintf(errmsg, max_msg_len, "%s: query string length (%d) exceeded maximm allowed length (%d) for query: %s\n",
                         caller, ll, (int) sizeof(query), query);
                return 1;
            }
        }

        i++;
    }

    if ((ll = safecat1(query, sizeof(query), ")")) < mq)
    {
    }
    else
    {
        snprintf(errmsg, max_msg_len, "%s: query string length (%d) exceeded maximum allowed length (%d) for query: %s\n",
                 caller, ll, (int) sizeof(query), query);
        return 1;
    }

    if (perform_insert_from_query_string(caller, conn, query, errmsg, max_msg_len) == 0)
    {
        rc = 1;
    }

    return rc;

}

/* ------------------------------------------------------------------------------------------------- */
/*                                                                                                   */
/* Function:   perform_drop                                                                          */
/*                                                                                                   */
/* Inputs:     caller                                                                                */
/*                                                                                                   */
/*             conn        An existing connection to the MYSQL database, usually set up by           */
/*                         do_connect()                                                              */
/*                                                                                                   */
/*             table       the name of the table from which the row is to be dropped                 */
/*                                                                                                   */
/*             where       specifies the contents oontents of the WHERE cause used in the DROP       */
/*                         - a NULL pointer value is not allowed and will result in an error         */
/*                                                                                                   */
/*             max_msg_len the max length (including the terminating 0) allowed in the errmsg        */
/*                                                                                                   */
/* Outputs:    errmsg      an error message indicating what went wrong if rc=1                       */
/*                                                                                                   */
/* Function:                                                                                         */
/*                                                                                                   */
/* Drops a row from the specified table                                                              */
/*                                                                                                   */
/* ------------------------------------------------------------------------------------------------- */

int perform_drop(char *caller,
                 MYSQL *conn,
                 char  *table,
                 char  *where,
                 char  *errmsg,
                 int   max_msg_len )
{

#undef  SUBNAME
#define SUBNAME "perform_drop"

    MYSQL_RES *res_set;
    int ll, rc = 0;
    char  query[1024];
    int   mq = sizeof(query);

    safecpy(errmsg, "", max_msg_len);
    snprintf(query, sizeof(query), "DROP %s WHERE ", table);

    if ((ll = safecat1(query, sizeof(query), where)) < mq)
    {
    }
    else
    {
        snprintf(errmsg, max_msg_len, "%s: query string length (%d) exceeded maximm allowed length (%d) for query: %s\n",
                 caller, ll, (int) sizeof(query), query);
        return 1;
    }

    if (perform_query (caller, conn, query) != 0)
    {
        return 1;
    }

    res_set = mysql_store_result(conn);

    if (res_set == NULL)    /* no result set was returned */
    {
        /* does the lack of a result set mean that an error  occurred or that no result set was returned? */
        if (mysql_field_count(conn) > 0)
        {
            /* a result set was expected, but mysql_store_result() did not return one; this means an error occurred */
            snprintf(errmsg, max_msg_len, "%s: no result set returned for query: %s\n", caller, query);
            return 1;
        }
        else
        {
            /* no result set was returned; query returned no data (it was a DROP so this is expected - no action needed) */
        }
    }
    else      /* a result set was returned */
    {
        /* free the result set */
        mysql_free_result(res_set);
    }

    return rc;

}

/* ------------------------------------------------------------------------------------------------- */
/*                                                                                                   */
/* Function:   check_for_res_set                                                                     */
/*                                                                                                   */
/* Inputs:     caller                                                                                */
/*                                                                                                   */
/*             sql_connection  An existing connection to the MYSQL database, usually set up by       */
/*                             do_connect()                                                          */
/*                                                                                                   */
/*             query           the query that has already been executed and for which we wish to     */
/*                             to see if there is a valid result set                                 */
/*                                                                                                   */
/* Outputs:                                                                                          */
/*                                                                                                   */
/* Returns     NULL if the res_set does not exists, non NULL if it does                              */
/*                                                                                                   */
/* Function:                                                                                         */
/*                                                                                                   */
/*                                                                                                   */
/* Warning - you must free the res_set that is returned after you have finished with it <<<<<        */
/* ------------------------------------------------------------------------------------------------- */

MYSQL_RES *check_for_res_set(char *caller, MYSQL *sql_connection, char *query)
{

    MYSQL_RES  *res_set;
    char msg[MAX_MSG_LEN];

    if ((res_set = mysql_store_result(sql_connection)) == NULL)
    {

        /* no result set was returned - that is an error as we are expecting one we think, even if it is empty */

        if (mysql_field_count(sql_connection) == 0)
        {

            /*  ah, we were not expecting query to return data really, eg it was a select, so all is okay after all */

        }
        else
        {

            /* mysql_store_result() should definitely have returned data - so there is an error condition */

            snprintf(msg, sizeof(msg), "%s: Error - no result returned for query: %s: mysql errno = %d (%s)\n",
                     caller, query, mysql_errno(sql_connection), mysql_error(sql_connection));
            print_msg_to_console(msg);

        }
    }

    return res_set;

}


